version: "3.9"

services:
  pf_orchard_localization:
    build:
      context: ..
      dockerfile: docker/Dockerfile.desktop-contained
    volumes:
      - ../:/home/vscode/my_python_packages/pf_orchard_localization:rw
      # Connect path to the local bag data
      - /media/jostan/MOAD1/research_data/2023-10-27_apple_localization/ros2_bags:/home/vscode/package_data/pf_orchard_localization_data/bag_data:rw
      # Connect path to the map data
      - /media/jostan/Portabits/pf_app_data/map_data_jazz_new.json:/home/vscode/package_data/pf_orchard_localization_data/map_data_jazz_new.json:ro
      # Connect path to the cached data
      - /home/jostan/Documents/2024-Oct-Cached_data/cached_data:/home/vscode/package_data/pf_orchard_localization_data/cached_data:rw
    network_mode: "host"
    runtime: nvidia   
    ipc: "host"
    user: vscode
    command: ["python3", "/home/vscode/pf_orchard_localization/scripts/run_pf_bag_app.py"]

