FROM osrf/ros:humble-desktop-full

# Add vscode user with same UID and GID as your host system
# (copied from https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user#_creating-a-nonroot-user)
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create a non-root user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && mkdir /home/$USERNAME/.config && chown ${USER_UID}:${USER_GID} /home/$USERNAME/.config

# Set up sudo
RUN apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    && rm -rf /var/lib/apt/lists/*

# Switch from root to user
USER $USERNAME

# Add user to video group to allow access to webcam
RUN sudo usermod --append --groups video $USERNAME

# Install needed packages
RUN sudo apt-get update && \
    sudo apt-get install -y --no-install-recommends\
    git \
    curl \
    unzip \
    python3-pyqt5 \
    python3-pip \
    libxcb-cursor0 && \
    # # libboost-python-dev \
    # # libgl1-mesa-glx \
    sudo rm -rf /var/lib/apt/lists/*

RUN pip install \
    matplotlib \
    opencv-python-headless \
    pyqtgraph \
    scipy \
    scikit-image  \
    rosbags \
    utm 

# Newest numpy version causes issues with some packages
RUN pip install numpy==1.26.4

# Update all packages
RUN sudo apt update && sudo apt upgrade -y

# Rosdep update
RUN rosdep update

# Create a directory for external repositories
RUN mkdir -p ~/my_python_packages
# Install map_data_tools, add version so that cache is invalidated when the version changes
ADD https://api.github.com/repos/Jostan86/map_data_tools/git/refs/heads/main /home/vscode/.map_data_tools_version.json
RUN git clone https://github.com/Jostan86/map_data_tools.git ~/my_python_packages/map_data_tools
RUN pip install ~/my_python_packages/map_data_tools

# Set up environment variables
ENV ROS_WS_ROOT=/home/${USERNAME}/ros2_ws
ENV ROS_DISTRO=humble

# Make a ros2 workspace
RUN mkdir -p ${ROS_WS_ROOT}/src

# Clone the interface pacakge into the workspace, the first line just invalidates the cache if the version of the package has changed
ADD https://api.github.com/repos/Jostan86/pf_orchard_interfaces/git/refs/heads/main /home/${USERNAME}/.pf_orchard_interfaces_version.json
RUN cd ${ROS_WS_ROOT}/src && git clone https://github.com/Jostan86/pf_orchard_interfaces.git

# Build the workspace
RUN cd ${ROS_WS_ROOT} && . /opt/ros/${ROS_DISTRO}/setup.sh && colcon build
# RUN cd ${ROS_WS_ROOT} && colcon build

# Copy the entrypoint script with the correct permissions
COPY docker/ros_entrypoint_jetson.sh /
RUN sudo chmod +x /ros_entrypoint_jetson.sh
ENTRYPOINT ["/ros_entrypoint_desktop.sh"]

RUN mkdir -p ~/tmp/runtime-${USERNAME}
RUN chmod -R 700 ~/tmp/runtime-${USERNAME}

# Add the ROS setup to the bashrc
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> ~/.bashrc
RUN echo "source ${ROS_WS_ROOT}/install/setup.bash" >> ~/.bashrc


### ------------------- ###
# Stuff added for 'contained' version
### ------------------- ###
ENV WIDTH_ESTIMATION_PACKAGE_PATH=/home/${USERNAME}/my_python_packages/trunk_width_estimation
ENV WIDTH_ESTIMATION_PACKAGE_DATA_PATH=/home/${USERNAME}/package_data/trunk_width_estimation_data

RUN mkdir -p ${WIDTH_ESTIMATION_PACKAGE_DATA_PATH}

# Install trunk width estimation package, add version so that cache is invalidated when the version changes
ADD https://api.github.com/repos/Jostan86/trunk_width_estimation/git/refs/heads/main ${WIDTH_ESTIMATION_PACKAGE_DATA_PATH}/.trunk_width_estimation_version.json
RUN git clone https://github.com/Jostan86/trunk_width_estimation.git ${WIDTH_ESTIMATION_PACKAGE_PATH}
RUN pip install ${WIDTH_ESTIMATION_PACKAGE_PATH}

# Download and unzip the data files
# Made links using instructions here: https://askubuntu.com/a/1211122
RUN curl -L "https://ivzkiw.bn.files.1drv.com/y4mDYz1RspetmfTiR6rwGZEAwpX9CTuxylqPxaC7cjgM0GRtMjdNNVPgpXThrFl5E83DQLQOZ7aYHZE8_utaQVjE8uMxtffzVmmpJWbzSlMnhuDsa9uCWWbjjaDvpvYIoEtYtBjYeEYrzOTkNbmPeCMN9-dlEtOxl_Ply5SUR66ixiWgU-Zm5AS7F23ecdpQkaExYU0kINte1nQIkL5tcUKEQ" \
    -o /tmp/main_data.zip\ 
    && unzip /tmp/main_data.zip -d ${WIDTH_ESTIMATION_PACKAGE_DATA_PATH} \
    && rm /tmp/main_data.zip
RUN curl -L "https://vmolxg.bn.files.1drv.com/y4mXpgogvrdIKNFt8NhRk8103kQ1D1LAwyK6I_oHI0HNIRx7eEaRPYO5kgu1t-gY_LlHGvuvQR0c1Xao002DNMohItm_SC0eyq8VgnmXW00fHqmCe5vNmKMpC5OlFe9Grnq9TutXeiEtlM5Uh_nDSHejkt7LqgK4MLHvIzwWtVZqFkSDq9iqMW9qDMddUODj1UkvgUEm0-cbBx6i4XQeNZWwA" \
    -o /tmp/analysis_data.zip \ 
    && unzip /tmp/analysis_data.zip -d ${WIDTH_ESTIMATION_PACKAGE_DATA_PATH} \
    && rm /tmp/analysis_data.zip

# Install the dependencies
RUN sudo apt-get update \
    && sudo apt-get install -y \
    # python3-opencv \
    libgl1 \
    libglib2.0-0 \
    libxrender1 \
    libsm6 \
    libxext6 \
    && sudo rm -rf /var/lib/apt/lists/*

RUN sudo apt-get update && \
    pip install \
    ultralytics \
    pydantic \
    && sudo rm -rf /var/lib/apt/lists/*

RUN sudo apt-get update && \
    sudo apt-get install -y \
    python3-opencv \
    && sudo rm -rf /var/lib/apt/lists/*

# Remove the default opencv-python package, i need only the headless version
RUN pip uninstall opencv-python -y

# Newest numpy version causes issues with some packages
RUN pip install numpy==1.26.4

# Update all packages
RUN sudo apt update && sudo apt upgrade -y && sudo rm -rf /var/lib/apt/lists/*

# RUN echo "export WIDTH_ESTIMATION_PACKAGE_PATH=/home/vscode/my_python_packages/trunk_width_estimation" >> ~/.bashrc

### ------------------- ###
### ------------------- ###

# These (should / should help to) force the gui applications to show up only on the remote display window
ENV DISPLAY=:1
ENV REMOTE_CONTAINERS_DISPLAY_SOCK=/tmp/.X11-unix/X0

# Set to remove a warning from pyqt
ENV XDG_RUNTIME_DIR=/tmp/runtime-${USERNAME}

# Copy the package into the container and install it
ENV WORKSPACE_ROOT=/home/${USERNAME}/my_python_packages/pf_orchard_localization
COPY --chown=${USERNAME}:${USERNAME} . ${WORKSPACE_ROOT}
RUN pip install -e ${WORKSPACE_ROOT}

USER root
