# ----------------------
# General parameters
# ----------------------

image_display_scale: 1.0

# The number of images to skip when loading the images from the file. (only used when loading images from the bag file)
every_nth_image: 3  # 1 means all images in the bag file, 2 means every other image, etc.

# Set to true to use a ros service to get the trunk width instead of loading the trunk width estimation module
use_ros_service_for_trunk_width: False

# Set to true to use the visual odometry to get the robot's velocity instead of the odometry topic
# If false, an odom topic must exist
use_visual_odom: False

# # ----------------------
# # Jazz apple orchard
# # ----------------------

# map_data_path: /home/vscode/app_data/map_data_jazz_new.json

# # rgb_topic: /throttled/registered/rgb/image
# # depth_topic: /throttled/registered/depth/image

# pf_config_file_path: /home/vscode/pf_orchard_localization/config/parameters_pf.yaml


map_data_path: /media/jostan/Portabits/pf_app_data/map_data_jazz_new.json
pf_config_file_path: /home/jostan/OneDrive/Docs/Grad_school/Research/code_projects/pf_orchard_localization/config/parameters_pf.yaml

rgb_topic: /camera/camera/color/image_raw
depth_topic: /camera/camera/aligned_depth_to_color/image_raw
odom_topic: /a200_0398/platform/odom/filtered
orientation_topic: /imu/data
gnss_uncorrected_topic: /ublox_gps_uncorrected/fix
gnss_corrected_topic: /ublox_gps_corrected/fix
