# ----------------------
# General parameters
# ----------------------

initial_data_time: 0  # seconds into the bag file
initial_data_file_index: 5  # index of the bag file

image_display_scale: 1.0

# The number of images to skip when loading the images from the file. (only used when loading images from the bag file)
every_nth_image: 3  # 1 means all images in the bag file, 2 means every other image, etc.

# Set to true to use a ros service to get the trunk width instead of loading the trunk width estimation module
use_ros_service_for_trunk_width: False

# Set to true to use the visual odometry to get the robot's velocity instead of the odometry topic
# If false, an odom topic must exist
use_visual_odom: False

# Whether to automatically load the next bag file when the current one is finished, helpful if bag files are split
auto_load_next_file: False

# # ----------------------
# # Jazz apple orchard - Oct. 2024
# # ----------------------
# rgb_topic: /camera/camera/color/image_raw
# depth_topic: /camera/camera/aligned_depth_to_color/image_raw
# odom_topic: /a200_0398/platform/odom/filtered
# orientation_topic: /imu/data
# gnss_uncorrected_topic: /ublox_gps_uncorrected/fix
# gnss_corrected_topic: /ublox_gps_corrected/fix

# ## Docker ##
# pf_config_file_path: /home/vscode/my_python_packages/pf_orchard_localization/config/parameters_pf.yaml
# map_data_path: /home/vscode/package_data/pf_orchard_localization_data/map_data_jazz_new.json
# data_file_dir: /home/vscode/package_data/pf_orchard_localization_data/bag_data/

# ----------------------
# Jazz apple orchard - Oct. 2023
# ----------------------
rgb_topic: /camera/color/image_raw
depth_topic: /camera/aligned_depth_to_color/image_raw
odom_topic: /odometry/filtered
orientation_topic: /imu/data # Not being used, adjust use_orientation_for_angular_velocity in parameters_pf.yaml to use
gnss_uncorrected_topic: /fix

## Docker ##
pf_config_file_path: /home/vscode/my_python_packages/pf_orchard_localization/config/parameters_pf.yaml
map_data_path: /home/vscode/package_data/pf_orchard_localization_data/map_data_jazz_new.json
data_file_dir: /home/vscode/package_data/pf_orchard_localization_data/bag_data/

# ----------------------
# Jazz apple orchard - Feb. 2023
# ----------------------
# rgb_topic: /registered/rgb/image
# depth_topic: /registered/depth/image
# odom_topic: /odometry/filtered

## Docker ##
# pf_config_file_path: /home/vscode/my_python_packages/pf_orchard_localization/config/parameters_pf.yaml
# map_data_path: /home/vscode/package_data/pf_orchard_localization_data/map_data_jazz_new.json
# data_file_dir: /home/vscode/package_data/pf_orchard_localization_data/bag_data/


