# ----------------------
# General parameters
# ----------------------

initial_data_time: 0  # seconds into the bag file
initial_data_file_index: 0  # index of the bag file

# Whether to automatically load the next bag file when the current one is finished, helpful if files are split
auto_load_next_file: False

# ----------------------
# Jazz apple orchard - Oct. 2024
# ----------------------
use_visual_odom: False

## Docker ##
pf_config_file_path: /home/vscode/my_python_packages/pf_orchard_localization/config/parameters_pf.yaml
map_data_path: /home/vscode/package_data/pf_orchard_localization_data/map_data_jazz_new.json
data_file_dir: /home/vscode/package_data/pf_orchard_localization_data/cached_data/
cached_image_dir: /home/vscode/package_data/pf_orchard_localization_data/cached_data/images
test_start_info_path: /home/vscode/package_data/pf_orchard_localization_data/cached_data/test_starts5.csv
test_results_save_path: /home/vscode/package_data/pf_orchard_localization_data/cached_data/results
