# Center of the area where particles are initially placed
start_pose_center_x: 11.5  # meters
start_pose_center_y: 12.42  # meters

# Density of particles in the initial distribution
particle_density: 200  # particles / m^2

# Size and orientation of the square shaped area where particles are initially placed
start_width: 10.0  # meters
start_height: 20.0  # meters
start_rotation: -32.0  # degrees

# Orientation of the particles in the initial distribution, so here particles will be oriented in theta = 53 - 63 degrees and 233 - 243 degrees
start_orientation_center: 58.0  # degrees
start_orientation_range: 10.0  # degrees
spawn_particles_in_both_directions: true

# Whether to stop the system when the filter has converged to a single cluster of particles (useful for testing)
stop_when_converged: true

# Translation between the camera and the robot base frame
#x_offset: 0.8
#y_offset: -0.55
x_offset: 0.0 # meters
y_offset: 0.0 # meters

# Size of the bins that the space containing the particles is divided into when calculating the spread of the particles
bin_size: 1.0 # meters
# Angle size that each bin is subdivided into when calculating the spread of the particles
bin_angle: 10 # degrees

# Parameters that are used to calculate how many particles to sample based on the spread of the particles
delta: 0.05
epsilon: 0.010

# The standard deviation of the expected noise from the range and bearing measurements of the trees made by the camera
range_sd: 0.5 # meters
bearing_sd: 0.3 # radians

# The standard deviation of the expected noise from the width measurements of the trees made by the camera
width_sd: 0.025

# The standard deviations of the amount of noise to add to the linear and angular movements of the particles.
r_angle: 20 # degrees
r_dist: 0.6 # meters
# This is used to standardize the amount of noise added to the linear and angular movements of the particles
# It is currently the fps at which the system was tuned (50 fps).
noise_fps: 50

# Whether to include the width measurement in the likelihood calculation
include_width: true

# Set to true to use the change in the orientation output from the imu to override any other the angular velocity
use_orientation_for_angular_velocity: False
# The number of readings to average to get the angular velocity
num_readings_for_angular_velocity: 5
# Set to true to use the global orientation output from the imu to help calculate the particle weights.
# If true, the orientation offset between the map and the sensor needs to be provided and accurate.
use_orientation_for_particle_weights: False
# The orientation offset between the map and the sensor, i.e. the orientation output's 'north' isn't aligned with the map's 'north', so this is the offset between them.
# This is specific to the orientation sensor used and needs to be tuned for each sensor - or an automatic process implemented.
orientation_offset: 1.02  # radians
# Option to help determine the offset, prints the offset between the imu orientation and the best particles orientation
# use_orientation_for_particle_weights should be set to false when using this option
print_orientation_offset: False
# The standard deviation of the expected noise from the orientation measurements made by the imu, used for the particle weight update.
orientation_sd: 0.4 # radians

# If the calculated time change between motion updates is greater than this value, the previous dt will be used or it will be skipped
motion_update_max_dt: 1.0  # seconds


# Maximum and minimum number of particles that the filter can have
# These are optional, if not included the filter will not have a maximum or minimum number of particles
max_num_particles: 2000000
min_num_particles: 100

